/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dados.Aluno;
import estruturas.ListaSimples;
import exception.EmptyListException;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinicius
 */
public class JFLista extends javax.swing.JFrame {

    ListaSimples<Aluno> listaAlunos;

    /**
     * Creates new form JFLista
     */
    public JFLista() {
        initComponents();
        listaAlunos = new ListaSimples<>("Lista de alunos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFnomeAluno = new javax.swing.JTextField();
        jTFIdadeAluno = new javax.swing.JTextField();
        jBAdicionaInicio = new javax.swing.JButton();
        jBAdicionaFim = new javax.swing.JButton();
        jBRemoveInicio = new javax.swing.JButton();
        jBRemoveFim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAImprimeLista = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        jLabel2.setText("Idade:");

        jBAdicionaInicio.setText("Adicionar Inicio");
        jBAdicionaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionaInicioActionPerformed(evt);
            }
        });

        jBAdicionaFim.setText("Adicionar Fim");
        jBAdicionaFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionaFimActionPerformed(evt);
            }
        });

        jBRemoveInicio.setText("Remover Inicio");
        jBRemoveInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRemoveInicioActionPerformed(evt);
            }
        });

        jBRemoveFim.setText("Remover Fim");
        jBRemoveFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRemoveFimActionPerformed(evt);
            }
        });

        jTAImprimeLista.setColumns(20);
        jTAImprimeLista.setRows(5);
        jScrollPane1.setViewportView(jTAImprimeLista);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFnomeAluno)
                            .addComponent(jTFIdadeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBAdicionaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBRemoveInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBAdicionaFim, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(jBRemoveFim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(51, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFnomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFIdadeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAdicionaInicio)
                    .addComponent(jBAdicionaFim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBRemoveInicio)
                    .addComponent(jBRemoveFim))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAdicionaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionaInicioActionPerformed

        if (jTFnomeAluno.getText().trim().isEmpty() || jTFIdadeAluno.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Insira os dados corretamente", "", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String nome = jTFnomeAluno.getText();
        int idade = Integer.parseInt(jTFIdadeAluno.getText());

        Aluno aluno = new Aluno(nome, idade);

        listaAlunos.insereNoInicio(aluno);

        atualizaVisualizacao();
        limpaCampos();
    }//GEN-LAST:event_jBAdicionaInicioActionPerformed

    private void jBRemoveInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRemoveInicioActionPerformed
        try {
            listaAlunos.removeDoInicio();
            atualizaVisualizacao();
        } catch (EmptyListException e) {
            JOptionPane.showMessageDialog(rootPane, "Impossivel excluir! Lista vazia", "", JOptionPane.ERROR_MESSAGE);
            jTAImprimeLista.setText("");
        }
    }//GEN-LAST:event_jBRemoveInicioActionPerformed

    private void jBAdicionaFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionaFimActionPerformed

        if (jTFnomeAluno.getText().trim().isEmpty() || jTFIdadeAluno.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Insira os dados corretamente", "", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String nome = jTFnomeAluno.getText();
        int idade = Integer.parseInt(jTFIdadeAluno.getText());

        Aluno aluno = new Aluno(nome, idade);

        listaAlunos.insereNoFim(aluno);

        atualizaVisualizacao();
        limpaCampos();
    }//GEN-LAST:event_jBAdicionaFimActionPerformed

    private void jBRemoveFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRemoveFimActionPerformed
        try {
            listaAlunos.removeDoInicio();
            atualizaVisualizacao();
        } catch (EmptyListException e) {
            JOptionPane.showMessageDialog(rootPane, "Impossivel excluir! Lista vazia", "", JOptionPane.ERROR_MESSAGE);
            jTAImprimeLista.setText("");
        }
    }//GEN-LAST:event_jBRemoveFimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLista().setVisible(true);
            }
        });
    }

    private void atualizaVisualizacao() {
        jTAImprimeLista.setText(listaAlunos.toString());
    }

    private void limpaCampos() {
        jTFIdadeAluno.setText("");
        jTFnomeAluno.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionaFim;
    private javax.swing.JButton jBAdicionaInicio;
    private javax.swing.JButton jBRemoveFim;
    private javax.swing.JButton jBRemoveInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAImprimeLista;
    private javax.swing.JTextField jTFIdadeAluno;
    private javax.swing.JTextField jTFnomeAluno;
    // End of variables declaration//GEN-END:variables
}
